/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void msDelay(uint32_t time){
	for(uint32_t i; i < time*4000; i++);
}

int main(void)
{

	uint32_t *pClkCtrlReg = (uint32_t)0x40023830;
	uint32_t *pGpioDModeReg = (uint32_t)0x40020C00;
	uint32_t *pGpioDOutReg = (uint32_t)0x40020C14;
	uint32_t *pGpioDInReg = (uint32_t)0x40020C10;
	uint32_t *pGpioDPullReg = (uint32_t)0x40020C0C;

	*pClkCtrlReg |= (1<<3); //enable clock for port D

	*pGpioDModeReg &= ~0xFF; //make pd0, pd1, pd2, pd3 as output registers CLEAR RESET

	*pGpioDModeReg |= 1<<6; // set pd3 as output
	*pGpioDModeReg |= 1<<4; // set pd2 as output
	*pGpioDModeReg |= 1<<2; // set pd1 as output
	*pGpioDModeReg |= 0x1;    // set pd0 as output

	*pGpioDOutReg |= 0xF; // set the pd0,pd1,pd2,pd3 as HIGH


	*pGpioDPullReg |= 1<<7; // set pd3 pull down register
	*pGpioDPullReg |= 1<<5; // set pd2 pull down register
	*pGpioDPullReg |= 1<<3; // set pd1 pull down register
	*pGpioDPullReg |= 0x2; // set pd0 pull down register



	*pGpioDPullReg |= 1<<22; // set pd11 pull up register
	*pGpioDPullReg |= 1<<20; // set pd10 pull up register
	*pGpioDPullReg |= 1<<18;  // set pd9 pull up register
	*pGpioDPullReg |= 1<<16; // set pd8 pull up register

	//*pGpioDModeReg &= ~0xFF; //make pd8, pd9, pd10, pd11 as input registers

			uint8_t  pin8_read;
			uint8_t  pin9_read;
			uint8_t  pin10_read;
			uint8_t  pin11_read;
			char button_pressed;

		    /* Loop forever */
	while(1){


		//check the first row

		*pGpioDOutReg &= ~0x1; // set the pd0 1st row as LOW

		if(pin8_read = (*pGpioDInReg & (1<<8)) == 0){
			msDelay(200);
			button_pressed = '1';
		}
		else if(pin9_read = (*pGpioDInReg & (1<<9)) == 0){
			msDelay(200);
			button_pressed = '2';
			//printf("Button pressed: %c", button_pressed);
		}
		else if(pin10_read = (*pGpioDInReg & (1<<10)) == 0){
			msDelay(200);
			button_pressed = '3';
		}
		else if(pin11_read = (*pGpioDInReg & (1<<11)) == 0){
			msDelay(200);
			button_pressed = 'A';
		}

		*pGpioDOutReg |= 0xF; // set the pd0,pd1,pd2,pd3 as HIGH


		//check the second row
		*pGpioDOutReg &= ~0x2; // set the pd1 2ond row as LOW

		if(pin8_read = (*pGpioDInReg & (1<<8)) == 0){
			msDelay(200);
			button_pressed = '4';
		}
		else if(pin9_read = (*pGpioDInReg & (1<<9)) == 0){
			msDelay(200);
			button_pressed = '5';
		}
		else if(pin10_read = (*pGpioDInReg & (1<<10)) == 0){
			msDelay(200);
			button_pressed = '6';
		}
		else if(pin11_read = (*pGpioDInReg & (1<<11)) == 0){
			msDelay(200);
			button_pressed = 'B';
		}
		*pGpioDOutReg |= 0xF; // set the pd0,pd1,pd2,pd3 as HIGH

		//check the third row
		*pGpioDOutReg &= ~(1<<2); // set the pd2 3ird row as LOW

		if(pin8_read = (*pGpioDInReg & (1<<8)) == 0){
			msDelay(200);
			button_pressed = '7';
		}
		else if(pin9_read = (*pGpioDInReg & (1<<9)) == 0){
			msDelay(200);
			button_pressed = '8';
		}
		else if(pin10_read = (*pGpioDInReg & (1<<10)) == 0){
			msDelay(200);
			button_pressed = '9';
		}
		else if(pin11_read = (*pGpioDInReg & (1<<11)) == 0){
			msDelay(200);
			button_pressed = 'C';
		}
		*pGpioDOutReg |= 0xF; // set the pd0,pd1,pd2,pd3 as HIGH

		//check the fourth row
		*pGpioDOutReg &= ~(1<<3); // set the pd3 4th row as LOW

		if(pin8_read = (*pGpioDInReg & (1<<8)) == 0){
			msDelay(200);
			button_pressed = '*';
		}
		else if(pin9_read = (*pGpioDInReg & (1<<9)) == 0){
			msDelay(200);
			button_pressed = '0';
		}
		else if(pin10_read = (*pGpioDInReg & (1<<10)) == 0){
			msDelay(200);
			button_pressed = '#';
		}
		else if(pin11_read = (*pGpioDInReg & (1<<11)) == 0){
			msDelay(200);
			button_pressed = 'D';
		}
		*pGpioDOutReg |= 0xF; // set the pd0,pd1,pd2,pd3 as HIGH
	}

}
